# Generated by Django 4.1.5 on 2023-01-29 20:33

from django.db import migrations, models
import django.db.models.deletion
import iainteractive.apps.common.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Grimorie",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("trefoil_leaves", models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="MagicAffinity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="Applicant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        max_length=20,
                        validators=[
                            iainteractive.apps.common.validators.validate_only_letters
                        ],
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        max_length=20,
                        validators=[
                            iainteractive.apps.common.validators.validate_only_letters
                        ],
                    ),
                ),
                ("identification", models.CharField(max_length=10)),
                (
                    "age",
                    models.SmallIntegerField(
                        validators=[iainteractive.apps.common.validators.validate_age]
                    ),
                ),
                (
                    "Grimorie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.grimorie",
                    ),
                ),
                (
                    "magic_affinity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.magicaffinity",
                    ),
                ),
            ],
        ),
    ]
