# Generated by Django 4.1.5 on 2023-01-29 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_rename_grimorie_applicant_grimorie"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="status",
            field=models.CharField(
                choices=[
                    ("0", "Initial"),
                    ("1", "In Review"),
                    ("2", "Rejected"),
                    ("3", "Approved"),
                ],
                default="0",
                max_length=1,
            ),
        ),
    ]
